/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("https://maven.pkg.github.com/cmu-pasta/fray")
            credentials {
                username = extra["gpr.user"] as String? ?: System.getenv("USERNAME")
                password = extra["gpr.key"] as String? ?: System.getenv("TOKEN")
            }
        }
    }
}

rootProject.name = "fray-examples"
